all :

build :

	./build.sh

inst :
	@[ -d ../INST/main-app/silp-dir/app-dir/bin ] || mkdir -p ../INST/main-app/silp-dir/app-dir/bin/
	@cp rcpsilp-1.0.jar  ../INST/main-app/silp-dir/app-dir/bin

clean :

	rm -fR build
	rm -f rcpsilp-1.0.jar
