all :

build :

inst :
	@[ -d ../INST/main-app/silp-dir/app-dir/bin ] || mkdir -p ../INST/main-app/silp-dir/app-dir/bin/
	@cp intrcp.env  ../INST/main-app/silp-dir/app-dir
	@cp intrcp.sh  ../INST/main-app/silp-dir/app-dir

clean :
